name: ChromeShack
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "testing build"
        required: true
        default: "testing"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: chromeshack
          path: dist/*.zip
