name: Playwright Tests
on:
  push:
    branches: [master, testing]
  pull_request:
    branches: [master, testing]

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install PNPM
        run: corepack enable
      - name: Install project dependencies
        run: pnpm install
      - name: Install test dependencies
        run: pnpm test:deps
      - name: Build in prod mode
        run: pnpm build
      - name: Run the test suite against Chromium
        run: pnpm test
        env:
          HOME: /root
          CI: true
          E2E_SHACKLI: ${{ secrets.E2E_SHACKLI }}
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: results/*
