name: Playwright Tests
on:
  push:
    branches:
      - master

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      # make sure to match this version to what's in package.json
      image: mcr.microsoft.com/playwright:v1.40.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'
      - name: Install project dependencies
        run: pnpm install
      - name: Install test dependencies
        run: pnpm test:deps
      - name: Build in prod mode
        run: pnpm build
      - name: Run the test suite against Chromium
        run: pnpm test
        env:
          HOME: /root
          CI: true
          E2E_SHACKLI: ${{ secrets.E2E_SHACKLI }}
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: results/*
